language: node_js

node_js:
    - "10"
    - "node"

env:
    global:
        - NODE_ENV=test

dist: trusty

cache:
    directories:
        - node_modules

install:
    - "make --silent install"

script: "make test"
