language: node_js

node_js:
    - "6"
    - "7"
    - "node"

env:
    global:
        - NODE_ENV=test

dist: trusty

cache:
    directories:
        - node_modules

install:
    - "make --silent install"
